server:
  port: 8888

spring:
  application:
    name: frame-demo
    #mysql
  datasource:
    url: jdbc:mysql://localhost:3306/frame-demo?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 900000
    type: com.zaxxer.hikari.HikariDataSource
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  type-aliases-package: com.ww.frame

logging:
  level:
    com.ww.frame: debug
  pattern:
    dateformat: HH:mm:ss:SSS